(function () {
  const sx7w8Pages = [
    {
      id: 'cover',
      pageNumber: 1,
      visualReference: 'mockup1',
      purpose: 'Signal a paid assessment product before the user reads the details.',
      contentRole: 'overview',
      layout: 'cover',
      eyebrow: 'ER Enneagram for Restoration',
      title: '적응형 에니어그램 심층 진단',
      subtitle: 'Enneagram Premium Report',
      resultCode: 'SX 7w8',
      identity: '강렬한 몰입과 주도권 속에서 살아 있음을 느끼되, 현실의 무게와 반복 앞에서는 자주 다음 장면으로 이동하려는 사람',
      details: [
        { label: 'Core Type', value: '7번 열정가' },
        { label: 'Dominant Instinct', value: '성적 본능 SX' },
        { label: 'Wing', value: '8번 날개' },
        { label: 'Report Focus', value: '몰입, 돌파력, 현실화, 회복' },
      ],
      closing: '이 결과지는 진단 점수를 해석의 출발점으로 삼아, 반복되는 반응과 회복 방향을 함께 읽도록 설계되었습니다.',
    },
    {
      id: 'one-glance',
      pageNumber: 2,
      visualReference: 'mockup2',
      purpose: 'Give the user an executive summary of the result.',
      contentRole: 'summary',
      layout: 'dashboard',
      eyebrow: 'One-Glance Result',
      title: '한눈에 보는 결과',
      deck: 'SX 7w8은 강렬한 연결과 새로운 자극을 향해 빠르게 움직이면서도, 움직이기 시작한 뒤에는 주도권을 잡고 판을 키우려는 힘이 강합니다.',
      metrics: [
        { label: '핵심 동기', value: '삶이 좁아지지 않고 생생하게 확장되기를 원함' },
        { label: '핵심 두려움', value: '갇히거나 지루해져서 활력을 잃는 것' },
        { label: '강점 언어', value: '점화, 설득, 돌파, 분위기 전환' },
        { label: '주의 신호', value: '마무리 회피, 과속, 피로 지연 인식' },
      ],
      quote: '이 유형은 즐거움을 찾는 사람으로만 설명되지 않습니다. 마음을 사로잡은 대상이 생기면, 그 장면을 실제로 열어젖히려는 실행 에너지가 함께 올라옵니다.',
    },
    {
      id: 'combination-deep-dive',
      pageNumber: 3,
      visualReference: 'mockup3',
      purpose: 'Create the premium "this is me" interpretation moment.',
      contentRole: 'interpretation',
      layout: 'editorial',
      eyebrow: 'Combination Deep Dive',
      title: '몰입이 불붙고, 돌파력이 방향을 잡을 때',
      quote: 'SX 7w8은 끌림을 느끼는 순간 마음만 앞서는 것이 아니라, 사람과 상황을 움직여 그 끌림을 현실의 장면으로 만들고 싶어합니다.',
      body: [
        '성적 본능의 7번은 특정 사람, 이야기, 비전, 분위기에 강하게 반응합니다. 평범한 일상보다 더 선명하고 밀도 있는 경험을 찾고, 마음이 붙는 순간 삶 전체가 밝아지는 듯한 감각을 느낄 수 있습니다.',
        '여기에 8번 날개가 더해지면 에너지는 단순한 기대감에 머물지 않습니다. 의견을 분명히 내고, 먼저 움직이며, 필요하면 규칙을 바꾸어서라도 흐름을 열려고 합니다.',
        '이 조합의 과제는 열정의 크기가 아니라 속도 조절입니다. 마음이 먼저 달려갈 때 몸과 일정과 관계의 실제 속도를 함께 확인해야, 추진력이 사람을 초대하는 힘으로 남습니다.',
      ],
      cards: [
        { title: 'Primary Energy', text: '강렬한 끌림을 실행으로 바꾸는 점화력' },
        { title: 'Relational Pattern', text: '깊은 연결을 원하지만 답답함이 오면 속도를 높임' },
        { title: 'Repeated Pattern', text: '시작은 빠르고 넓지만 반복 관리에서 긴장이 커짐' },
      ],
    },
    {
      id: 'strengths-fit',
      pageNumber: 4,
      visualReference: 'mockup4',
      purpose: 'Turn diagnosis into usable language.',
      contentRole: 'strengths',
      layout: 'quadrants',
      eyebrow: 'Strengths And Fit',
      title: '강점이 살아나는 자리와 과해지는 자리',
      sections: [
        {
          title: '잘 살아나는 힘',
          items: [
            '정체된 분위기에 생기를 넣고 사람들이 다시 움직이게 만듭니다.',
            '아이디어를 말로만 남기지 않고 실제 일정과 행동으로 당겨옵니다.',
            '위험을 감수해야 하는 초반 국면에서 결정을 늦추지 않습니다.',
          ],
        },
        {
          title: '과사용될 때',
          items: [
            '상대가 따라오는지 확인하기 전에 이미 결론을 밀어붙일 수 있습니다.',
            '불편한 감정을 설명하기보다 새 계획을 추가해 긴장을 덮을 수 있습니다.',
            '몸의 피로와 재정 부담을 나중 문제로 미루기 쉽습니다.',
          ],
        },
        {
          title: '잘 맞는 환경',
          items: [
            '비전 제시와 현장 실행이 함께 필요한 프로젝트',
            '빠른 실험을 허용하되 마감과 역할이 분명한 팀',
            '사람을 설득하고 참여시키는 커뮤니티형 과업',
          ],
        },
        {
          title: '소모가 큰 환경',
          items: [
            '승인 절차만 길고 실제 변화가 거의 없는 조직',
            '세부 정리만 반복되고 자율성이 낮은 역할',
            '열정을 냉소로만 반응하는 관계 문화',
          ],
        },
      ],
      coachingQuestions: [
        '지금 내가 넓히려는 일은 실제로 끝낼 구조를 갖고 있는가?',
        '내가 먼저 느낀 확신을 다른 사람도 이해할 시간을 주고 있는가?',
        '오늘 줄여야 할 약속 하나는 무엇인가?',
      ],
    },
    {
      id: 'score-flow',
      pageNumber: 5,
      visualReference: 'mockup5',
      purpose: 'Show the result was computed, not guessed.',
      contentRole: 'evidence',
      layout: 'scoreboard',
      eyebrow: 'Score Flow',
      title: '점수 흐름이 보여주는 패턴',
      deck: '이 페이지는 해석의 근거를 시각화합니다. 본능, 날개, 상위 유형 흐름을 함께 보면 왜 SX 7w8로 읽히는지 더 분명해집니다.',
      panels: [
        { title: 'Dominant Instinct', value: 'SX', note: '특정 대상과 강렬한 연결을 향해 에너지가 먼저 움직입니다.' },
        { title: 'Wing Pull', value: '8 Wing', note: '생각보다 행동이 빠르고, 필요할 때 직접 밀고 나갑니다.' },
        { title: 'Growth Direction', value: '5번', note: '관찰, 정리, 에너지 보존이 회복의 통로가 됩니다.' },
        { title: 'Stress Direction', value: '1번', note: '압박이 커지면 기준과 비판이 날카로워질 수 있습니다.' },
      ],
    },
    {
      id: 'repeated-cycle',
      pageNumber: 6,
      visualReference: 'mockup6',
      purpose: 'Help the user recognize the automatic loop.',
      contentRole: 'pattern',
      layout: 'timeline',
      eyebrow: 'Repeated Cycle',
      title: '반복되는 자동 루프',
      steps: [
        { label: '1', title: '강한 끌림', text: '사람, 아이디어, 기회가 마음을 사로잡으면 에너지가 빠르게 올라옵니다.' },
        { label: '2', title: '판 키우기', text: '가능하다고 느낀 순간 사람을 모으고 방향을 제안하며 속도를 냅니다.' },
        { label: '3', title: '현실의 저항', text: '일정, 돈, 몸, 책임 같은 구체 조건이 등장하며 답답함이 생깁니다.' },
        { label: '4', title: '압박 또는 이탈', text: '더 세게 추진하거나, 마음이 이미 다른 장면을 탐색하기 시작합니다.' },
        { label: '5', title: '남은 미완료', text: '초기 열정은 컸지만 정리와 마무리가 늦어져 피로가 쌓입니다.' },
      ],
      formation: '이 루프는 게으름보다 과속에 가깝습니다. 마음이 생생함을 잃을까 두려울수록, 멈춰서 정리하기보다 더 넓은 선택지를 찾습니다.',
      restorationPreview: '회복은 속도를 잃는 일이 아니라, 한 가지를 끝까지 돌보는 힘을 회복하는 일입니다.',
    },
    {
      id: 'life-application',
      pageNumber: 7,
      visualReference: 'mockup7',
      purpose: 'Translate the result into daily behavior.',
      contentRole: 'application',
      layout: 'applications',
      eyebrow: 'Life Application',
      title: '일상에서 드러나는 세 가지 장면',
      sections: [
        {
          title: '일과 커리어',
          strength: '새 프로젝트를 시작하고 사람을 설득하는 순간 강점이 선명해집니다.',
          watch: '운영의 세부가 길어질 때 집중이 분산될 수 있습니다.',
          practice: '회의 전 “오늘 결정할 한 가지”를 적고, 끝난 뒤 담당자와 마감일을 확인합니다.',
        },
        {
          title: '관계',
          strength: '상대가 잊고 있던 기대와 생기를 다시 꺼내도록 돕습니다.',
          watch: '상대의 느린 반응을 거절로 해석하면 말의 압력이 높아질 수 있습니다.',
          practice: '중요한 대화에서는 두 문장 말한 뒤 한 번 질문으로 멈춥니다.',
        },
        {
          title: '부모됨과 멘토링',
          strength: '아이와 후배에게 더 큰 그림을 보여주고 도전할 용기를 줍니다.',
          watch: '상대가 아직 준비되지 않았는데 더 큰 목표를 제시할 수 있습니다.',
          practice: '격려 전에 현재 감정과 필요한 도움을 먼저 확인합니다.',
        },
      ],
      signals: [
        { label: 'Stress Signal', text: '말이 빨라지고 일정이 늘어나며 쉬는 시간이 사라집니다.' },
        { label: 'Recovery Signal', text: '한 약속을 줄이고, 이미 시작한 일을 정리할 여백을 확보합니다.' },
      ],
    },
    {
      id: 'motivation-fear',
      pageNumber: 8,
      visualReference: 'mockup8',
      purpose: 'Name the engine and the drain behind the pattern.',
      contentRole: 'motivation',
      layout: 'two-column',
      eyebrow: 'Core Motivation And Fear',
      title: '무엇이 움직이게 하고, 무엇이 에너지를 빼앗는가',
      columns: [
        {
          title: '핵심 동기',
          text: '삶이 좁아지지 않고, 더 선명한 경험과 연결 속에서 살아 있음을 느끼고 싶습니다. 이 동기는 사람을 깨우고 상황을 전진시키는 선물이 됩니다.',
          bullets: [
            '새로운 시야를 여는 대화',
            '긴장을 환기시키는 유머와 상상력',
            '위험 앞에서 움츠러들지 않는 추진',
          ],
        },
        {
          title: '핵심 두려움',
          text: '선택지가 사라지고 지루함 속에 갇히는 느낌을 견디기 어렵습니다. 이 두려움이 커질수록 반복, 기다림, 정리의 과정을 손실처럼 느낄 수 있습니다.',
          bullets: [
            '현실 조건을 제한으로만 해석함',
            '미완료보다 새 출발을 더 가볍게 느낌',
            '불편한 감정을 계획으로 덮음',
          ],
        },
      ],
      balance: '균형은 더 작은 삶을 선택하는 것이 아니라, 선택한 삶을 끝까지 책임질 만큼 리듬을 조정하는 것입니다.',
    },
    {
      id: 'possibility-keys',
      pageNumber: 9,
      visualReference: 'mockup9',
      purpose: 'Show internal resources and practical growth keys.',
      contentRole: 'growth',
      layout: 'keys',
      eyebrow: 'Keys For Growth',
      title: '이미 가진 자원과 성장의 열쇠',
      resources: [
        { title: '상상력', text: '막힌 장면에서 다른 접근을 떠올리는 속도가 빠릅니다.' },
        { title: '용기', text: '불확실한 상황에서도 먼저 손을 들고 시작할 수 있습니다.' },
        { title: '전염력', text: '말과 분위기로 사람의 기대치를 다시 끌어올립니다.' },
      ],
      sequence: [
        '새로운 일을 추가하기 전 현재 약속을 목록화합니다.',
        '지금 가장 피하고 싶은 현실 조건을 하나만 적습니다.',
        '그 조건을 해결할 최소 행동을 20분 단위로 줄입니다.',
        '도움을 요청할 사람과 요청 문장을 정합니다.',
        '마무리 기준을 숫자나 날짜로 남깁니다.',
      ],
      closing: '성장은 더 많은 자극을 확보하는 데서가 아니라, 선택한 방향을 돌볼 체력을 남기는 데서 시작됩니다.',
    },
    {
      id: 'sustainable-change',
      pageNumber: 10,
      visualReference: 'mockup10',
      purpose: 'Make growth actionable without sounding like homework.',
      contentRole: 'change',
      layout: 'journey',
      eyebrow: 'Sustainable Change',
      title: '오래 가는 변화를 위한 원칙',
      principles: [
        { title: '속도보다 리듬', text: '처음의 열기가 아니라 다음 주에도 반복할 수 있는 구조를 기준으로 삼습니다.' },
        { title: '확장보다 완결', text: '새로운 선택지를 열기 전에 이미 시작한 한 가지를 닫는 경험이 필요합니다.' },
        { title: '주도보다 동의', text: '사람을 이끄는 힘은 상대가 이해하고 따라올 여지를 줄 때 더 건강해집니다.' },
      ],
      journeyNote: '당신의 에너지는 줄여야 할 문제가 아니라 다듬어야 할 선물입니다. 방향을 좁히는 훈련은 생기를 빼앗는 것이 아니라, 생기가 오래 남도록 돕습니다.',
      nextCards: [
        { title: '오늘', text: '미완료 하나를 정하고 30분만 정리합니다.' },
        { title: '이번 주', text: '몸, 돈, 일정 중 가장 약한 영역을 점검합니다.' },
        { title: '이번 달', text: '한 사람에게 내 속도가 어땠는지 피드백을 듣습니다.' },
      ],
    },
    {
      id: 'core-type-profile',
      pageNumber: 11,
      visualReference: 'type-profile',
      purpose: 'Explain the core type beyond the combination page.',
      contentRole: 'type-depth',
      layout: 'profile',
      eyebrow: 'Core Type 7',
      title: '7번의 중심: 즐거움보다 더 깊은 “막히지 않음”의 욕구',
      body: [
        '7번은 단지 재미를 좋아하는 유형이 아닙니다. 더 정확히는 고통, 제한, 결핍에 압도되지 않기 위해 마음속에서 다음 선택지를 빠르게 만듭니다.',
        '건강할 때 이 힘은 사람들에게 시야를 열어주고, 어려운 상황에서도 창의적 대응을 찾게 합니다. 그러나 불안이 커지면 생각이 많아지고 약속이 늘어나며, 실제로 중요한 감정은 뒤로 밀립니다.',
      ],
      attributes: [
        { label: '중심 욕구', value: '열린 선택지와 생동감 있는 삶' },
        { label: '자동 습관', value: '불편함을 다른 계획으로 전환' },
        { label: '회복 방향', value: '관찰, 단순화, 한 가지에 머무름' },
      ],
    },
    {
      id: 'instinct-stack',
      pageNumber: 12,
      visualReference: 'instinct-stack',
      purpose: 'Explain SX dominance and stack implications.',
      contentRole: 'instinct-depth',
      layout: 'stack',
      eyebrow: 'Instinct Stack',
      title: 'SX가 앞서고 SP가 약할 때',
      body: '성적 본능이 앞서면 에너지는 특정 대상과의 강한 연결로 먼저 향합니다. 보조 사회적 본능은 이 연결을 관계망과 영향력으로 확장합니다. 자기보존 본능이 약하면 생활의 기초를 챙기는 감각이 늦게 켜집니다.',
      stack: [
        { code: 'SX', label: '강렬한 연결', text: '마음이 붙는 대상에게 빠르게 집중합니다.' },
        { code: 'SO', label: '의미와 영향력', text: '사람들에게 좋은 방향을 만들고 싶어합니다.' },
        { code: 'SP', label: '생활 기반', text: '휴식, 돈, 루틴은 의식적으로 관리해야 합니다.' },
      ],
      application: [
        '관계에서는 깊이 들어가지만 속도 차이를 놓칠 수 있습니다.',
        '일에서는 네트워크를 움직이나 개인 에너지 예산을 과소평가할 수 있습니다.',
        '영성에서는 뜨거운 결단 뒤의 조용한 지속이 훈련 포인트입니다.',
      ],
    },
    {
      id: 'wing-adjacent',
      pageNumber: 13,
      visualReference: 'wing-profile',
      purpose: 'Explain what the 8 wing adds and distorts.',
      contentRole: 'wing-depth',
      layout: 'comparison',
      eyebrow: 'Wing And Adjacent Types',
      title: '8번 날개가 더하는 힘',
      body: '8번 날개는 7번의 머릿속 선택지를 몸으로 밀어내는 힘을 줍니다. 그래서 이 결과는 부드러운 낙관보다 직접적인 주장, 빠른 행동, 경계 돌파의 색이 강합니다.',
      comparisons: [
        { title: '7w6와 다르게', text: '불안을 질문과 확인으로 풀기보다 행동과 주장으로 넘어서려 합니다.' },
        { title: '순수 7번보다', text: '상상 속 탐색에 오래 머물지 않고 판을 만들려는 의지가 큽니다.' },
        { title: '8번처럼 보일 때', text: '주도성이 강해도 중심 두려움은 통제 상실보다 갇힘과 결핍에 더 가깝습니다.' },
      ],
    },
    {
      id: 'work-vocation-fit',
      pageNumber: 14,
      visualReference: 'work-fit',
      purpose: 'Bring career value without overclaiming.',
      contentRole: 'work',
      layout: 'career',
      eyebrow: 'Work And Vocation',
      title: '일에서 빛나는 조건',
      sections: [
        {
          title: '에너지가 살아나는 책임',
          items: [
            '초기 기획과 런칭',
            '사람을 모으는 커뮤니케이션',
            '막힌 상황의 전환 전략',
            '현장성과 빠른 판단이 필요한 역할',
          ],
        },
        {
          title: '주의해야 할 업무 조건',
          items: [
            '권한 없이 책임만 커지는 구조',
            '반복 행정이 대부분인 장기 운영',
            '성과보다 절차 준수만 강조되는 환경',
            '휴식 없는 확장 압력',
          ],
        },
      ],
      questions: [
        '이 역할은 내게 시작의 자유뿐 아니라 마무리의 지원도 제공하는가?',
        '내가 맡을 영향력의 범위와 책임의 경계가 분명한가?',
      ],
    },
    {
      id: 'team-leadership',
      pageNumber: 15,
      visualReference: 'team-fit',
      purpose: 'Translate the type into team communication and leadership.',
      contentRole: 'team',
      layout: 'team',
      eyebrow: 'Team Fit',
      title: '팀 안에서의 기여와 조율',
      cards: [
        { title: '기여', text: '팀이 두려움 때문에 멈출 때 실험 가능한 다음 행동을 제안합니다.' },
        { title: '소통', text: '큰 그림을 먼저 말하고, 세부는 신뢰하는 사람과 나누어 설계할 때 안정됩니다.' },
        { title: '리더십', text: '초반 추진에는 강하지만, 중반 이후 운영 리듬을 맡아줄 파트너가 필요합니다.' },
        { title: '팔로워십', text: '의미와 자율성이 보이면 헌신하지만, 설명 없는 통제에는 빠르게 저항합니다.' },
      ],
      repair: '팀에서 신뢰를 지키려면 “할 수 있다”는 말 뒤에 범위, 시간, 담당자를 함께 붙이는 습관이 중요합니다.',
    },
    {
      id: 'relationships-closeness',
      pageNumber: 16,
      visualReference: 'relationships',
      purpose: 'Make the report emotionally useful.',
      contentRole: 'relationship',
      layout: 'relationship',
      eyebrow: 'Relationships',
      title: '가까움, 속도, 그리고 기다림',
      body: [
        'SX 7w8은 관계 안에서 강한 생동감을 원합니다. 마음이 통한다고 느끼면 거리감이 빠르게 줄어들고, 함께 만들 미래를 상상하기 시작합니다.',
        '그러나 상대가 조심스럽거나 감정 정리가 느릴 때, 이 사람은 기다림을 관계의 후퇴처럼 느낄 수 있습니다. 그 순간 말을 더 많이 하거나 상황을 주도하려는 반응이 나올 수 있습니다.',
      ],
      prompts: [
        '내가 지금 상대를 초대하고 있는가, 결론으로 밀고 있는가?',
        '상대의 침묵을 거절로 해석하기 전에 확인한 사실은 무엇인가?',
        '이 대화에서 내가 견뎌야 할 감정은 무엇인가?',
      ],
    },
    {
      id: 'family-conflict-repair',
      pageNumber: 17,
      visualReference: 'family-repair',
      purpose: 'Name family and conflict repair moves.',
      contentRole: 'family',
      layout: 'repair',
      eyebrow: 'Family And Conflict',
      title: '갈등 속에서 다시 연결되는 법',
      sections: [
        {
          title: '가족이 경험할 수 있는 모습',
          text: '열정적이고 든든하지만, 때로는 대화의 온도와 속도가 높아져 가족이 따라가기 어렵다고 느낄 수 있습니다.',
        },
        {
          title: '오해가 생기는 지점',
          text: '본인은 살리려고 말했는데, 상대는 평가받거나 압박받는 느낌을 받을 수 있습니다.',
        },
        {
          title: '수리 문장',
          text: '“내가 너무 빨리 갔어. 지금 네가 실제로 느낀 것을 먼저 듣고 싶어.”',
        },
      ],
      practices: [
        '갈등 직후 해결책을 말하기 전 감정 단어를 하나만 확인합니다.',
        '아이 또는 배우자의 반응 속도를 고치려 하지 말고 기준으로 삼습니다.',
        '사과는 의도 설명보다 상대가 받은 영향을 인정하는 문장으로 시작합니다.',
      ],
    },
    {
      id: 'stress-restoration-plan',
      pageNumber: 18,
      visualReference: 'stress-plan',
      purpose: 'Provide practical next steps for stress and recovery.',
      contentRole: 'stress',
      layout: 'plan',
      eyebrow: 'Stress And Restoration',
      title: '압박이 커질 때의 회복 계획',
      signals: [
        { label: '초기 신호', text: '말의 속도가 빨라지고 “일단 해보자”가 늘어납니다.' },
        { label: '중간 신호', text: '몸의 피로를 무시한 채 약속과 연락을 추가합니다.' },
        { label: '위험 신호', text: '사람들이 따라오지 않는다고 느끼며 짜증과 비판이 올라옵니다.' },
      ],
      reset: [
        '오늘 새로 잡은 약속을 하나 보류합니다.',
        '몸 상태, 돈, 일정 중 가장 부담이 큰 영역을 숫자로 확인합니다.',
        '마무리할 일 하나를 정하고 45분만 닫습니다.',
      ],
      reflection: '주간 점검 질문: 이번 주 내가 피하려고 더 크게 만든 일은 무엇이었는가?',
    },
    {
      id: 'faith-restoration',
      pageNumber: 19,
      visualReference: 'faith-restoration',
      purpose: 'Offer ER Christian restoration language as invitation.',
      contentRole: 'faith',
      layout: 'faith',
      eyebrow: 'Faith And Restoration',
      title: '회복을 향한 신앙적 초대',
      body: '이 페이지는 강요가 아니라 초대입니다. 신앙의 언어가 익숙하다면, 이 패턴은 “내가 계속 움직여야 안전하다”는 믿음을 내려놓고, 이미 주어진 사랑 안에서 멈추는 연습으로 이어질 수 있습니다.',
      movements: [
        { label: 'False Belief', text: '멈추면 나는 갇히고, 생기를 잃고, 놓칠 것이다.' },
        { label: 'Gospel Truth', text: '하나님의 사랑은 내 열정의 크기보다 먼저 나를 붙듭니다.' },
        { label: 'Turning', text: '더 크게 벌리기 전에 주어진 자리에서 정직하게 응답합니다.' },
        { label: 'Prayer', text: '주님, 내가 달려가야만 안전하다는 마음을 내려놓고 오늘의 책임 안에서 평안을 배우게 하소서.' },
      ],
    },
    {
      id: 'summary-next-steps',
      pageNumber: 20,
      visualReference: 'summary-next',
      purpose: 'Close like a professional report and offer next steps.',
      contentRole: 'next-step',
      layout: 'summary',
      eyebrow: 'Summary And Next Steps',
      title: '기억해야 할 핵심과 다음 단계',
      remember: [
        '당신의 강점은 사람과 상황에 생기를 불어넣고 실제 움직임을 만드는 데 있습니다.',
        '가장 큰 성장 지점은 새로운 장면을 더하는 것보다 선택한 일을 돌볼 리듬을 세우는 것입니다.',
        '관계에서는 속도보다 동의가 신뢰를 지켜줍니다.',
        '회복은 열정을 부정하지 않고 현실의 조건과 함께 다루는 데서 깊어집니다.',
      ],
      nextSteps: [
        { title: 'Typing Consultation', text: '결과가 맞는지 코치와 함께 검토하고 실제 사례로 확인합니다.' },
        { title: 'Restoration Coaching', text: '반복 루프와 회복 루틴을 개인 상황에 맞게 설계합니다.' },
        { title: 'Relationship Debrief', text: '가까운 관계에서 속도와 압박이 어떻게 나타나는지 함께 읽습니다.' },
      ],
      disclaimer: '본 결과지는 자기이해와 코칭 대화를 위한 자료이며, 의학적 또는 임상적 진단을 대체하지 않습니다.',
    },
  ];

  window.ERReportV2Data = {
    defaultPageCount: 20,
    forbiddenPhrases: ['조합만의 ' + '화학'],
    samples: {
      sx_7_w8: {
        titleCode: 'SX 7w8',
        pages: sx7w8Pages,
      },
    },
  };
})();
