#!/usr/bin/env node
// Generate browser-safe premium report chemistry data from content JSON.
import fs from 'node:fs';
import path from 'node:path';

const ROOT = process.cwd();
const CHEMISTRY_DIR = path.join(ROOT, 'docs/report-content/chemistry');
const OUTPUT_PATH = path.join(ROOT, 'js/report-chemistry-data.js');
const args = new Set(process.argv.slice(2));

function readChemistryCards() {
  if (!fs.existsSync(CHEMISTRY_DIR)) {
    throw new Error(`Missing directory: ${path.relative(ROOT, CHEMISTRY_DIR)}`);
  }

  return fs.readdirSync(CHEMISTRY_DIR)
    .filter((name) => name.endsWith('.json'))
    .sort()
    .map((name) => {
      const filePath = path.join(CHEMISTRY_DIR, name);
      const card = JSON.parse(fs.readFileSync(filePath, 'utf8'));
      return [
        card.combination_key,
        {
          schema_version: card.schema_version,
          combination_key: card.combination_key,
          core: card.core,
          dominant_instinct: card.dominant_instinct,
          secondary_instinct: card.secondary_instinct,
          blind_instinct: card.blind_instinct,
          wing: card.wing,
          status: card.status,
          identity_sentence: card.identity_sentence,
          display: card.display,
        },
      ];
    });
}

function buildRuntimeSource(cards) {
  const cardsObject = Object.fromEntries(cards);
  const serializedCards = JSON.stringify(cardsObject, null, 2)
    .split('\n')
    .map((line, index) => (index === 0 ? line : `  ${line}`))
    .join('\n');

  return `// ER premium report chemistry runtime data.
// Generated by scripts/build_report_chemistry_data.mjs. Do not edit manually.
(function () {
  'use strict';

  const REPORT_CHEMISTRY_CARDS = ${serializedCards};

  function getChemistryCard(key) {
    return REPORT_CHEMISTRY_CARDS[key] || null;
  }

  const api = { cards: REPORT_CHEMISTRY_CARDS, get: getChemistryCard };

  if (typeof module !== 'undefined' && module.exports) module.exports = api;
  if (typeof window !== 'undefined') window.ERReportChemistry = api;
})();
`;
}

function main() {
  const output = buildRuntimeSource(readChemistryCards());

  if (args.has('--check')) {
    const current = fs.existsSync(OUTPUT_PATH) ? fs.readFileSync(OUTPUT_PATH, 'utf8') : '';
    if (current !== output) {
      console.error(`${path.relative(ROOT, OUTPUT_PATH)} is stale. Run: node scripts/build_report_chemistry_data.mjs`);
      process.exit(1);
    }
    console.log(`${path.relative(ROOT, OUTPUT_PATH)} is up to date`);
    return;
  }

  fs.writeFileSync(OUTPUT_PATH, output);
  console.log(`Generated ${path.relative(ROOT, OUTPUT_PATH)}`);
}

main();
